apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruddickmg/bythepeoples:api-server
  labels:
    app: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: ruddickmg/bythepeoples:api-server
          ports:
            - containerPort: 3000