pub const HOURS_IN_A_DAY: u64 = 24;
pub const MINUTES_IN_AN_HOUR: u64 = 60;
pub const SECONDS_IN_A_MINUTE: u64 = 60;
pub const ONE_DAY: u64 = SECONDS_IN_A_MINUTE * MINUTES_IN_AN_HOUR * HOURS_IN_A_DAY;
