use crate::configuration::ACCOUNT_LOCK_DURATION_IN_MINUTES;

pub const SECONDS_IN_A_MINUTE: u64 = 60;
pub const ACCOUNT_LOCK_DURATION_IN_SECONDS: u64 =
    ACCOUNT_LOCK_DURATION_IN_MINUTES * SECONDS_IN_A_MINUTE;
