pub mod database;
pub mod hash;
pub mod jwt;

const SECONDS_IN_A_MINUTE: u64 = 60;
const ACCOUNT_LOCK_DURATION_IN_MINUTES: u64 = 30;
pub const ACCOUNT_LOCK_DURATION_IN_SECONDS: u64 =
    ACCOUNT_LOCK_DURATION_IN_MINUTES * SECONDS_IN_A_MINUTE;
pub const ALLOWED_FAILED_LOGIN_ATTEMPTS: i32 = 50;
